name: 'GitHub Version Action'
author: 'James Elliott, Deep Symmetry'
description: 'GitHub Action setting an env variable to help create files based on Maven version inferred from git tags.'
inputs:
  var-name:  # id of input
    description: 'Variable to create, defaults to git_version'
    required: false
    default: 'git_version'
  tag-var-name:
    description: 'Optional variable to create for raw git tag name'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-commit'
  color: 'purple'
